// GENERATED FILE — do not edit by hand.
// Generated by xinyu/scripts/migrate_ios_assets.py from iOS xcassets.
// Re-run the script to regenerate.

/// 图片资源路径常量（与原 iOS imageset 名 1:1 对应）。
class AppAssets {
  AppAssets._();

  static const String aiAgentAvatar = 'assets/images/ai_agent_avatar.png';
  static const String aiDeerGreeting = 'assets/images/ai_deer_greeting.png';
  static const String aiInputFile = 'assets/images/ai_input_file.png';
  static const String aiInputKeyboard = 'assets/images/ai_input_keyboard.png';
  static const String aiInputVoice = 'assets/images/ai_input_voice.png';
  static const String aiOnlineIcon = 'assets/images/ai_online_icon.png';
  static const String aiPanelAlbum = 'assets/images/ai_panel_album.png';
  static const String aiPanelCamera = 'assets/images/ai_panel_camera.png';
  static const String aiPanelFile = 'assets/images/ai_panel_file.png';
  static const String aiSparkle = 'assets/images/ai_sparkle.png';
  static const String bgHeaderGradient = 'assets/images/bg_header_gradient.png';
  static const String cardArrow = 'assets/images/card_arrow.png';
  static const String chatPanelBreath = 'assets/images/chat_panel_breath.png';
  static const String chatPanelMeditation =
      'assets/images/chat_panel_meditation.svg';
  static const String chatPanelSleep = 'assets/images/chat_panel_sleep.png';
  static const String chatPanelWhiteNoise =
      'assets/images/chat_panel_white_noise.svg';
  static const String chatPanelWoodenFish =
      'assets/images/chat_panel_wooden_fish.png';
  static const String consultantAvatar1 =
      'assets/images/consultant_avatar_1.png';
  static const String consultantAvatar2 =
      'assets/images/consultant_avatar_2.png';
  static const String consultantDetailTopBg =
      'assets/images/consultant_detail_top_bg.png';
  static const String homeAssessmentAnxiety =
      'assets/images/home_assessment_anxiety.png';
  static const String homeAssessmentDepression =
      'assets/images/home_assessment_depression.png';
  static const String homeAssessmentListAnxiety =
      'assets/images/home_assessment_list_anxiety.png';
  static const String homeAssessmentListDepression =
      'assets/images/home_assessment_list_depression.png';
  static const String homeAssessmentListEfficacy =
      'assets/images/home_assessment_list_efficacy.png';
  static const String homeAssessmentListGad =
      'assets/images/home_assessment_list_gad.png';
  static const String homeAssessmentListHealth =
      'assets/images/home_assessment_list_health.png';
  static const String homeAssessmentListInsomnia =
      'assets/images/home_assessment_list_insomnia.png';
  static const String homeAssessmentMbti =
      'assets/images/home_assessment_mbti.png';
  static const String homeAssessmentReportBg =
      'assets/images/home_assessment_report_bg.png';
  static const String homeAssessmentReportGauge =
      'assets/images/home_assessment_report_gauge.png';
  /// 测评报告内容出处图标（iOS home_assessment_source / xinxilaiyuan，展示 10×10）
  static const String homeAssessmentSource =
      'assets/images/home_assessment_source.png';
  static const String homeCalendarIcon = 'assets/images/home_calendar_icon.png';
  static const String homeConsultant = 'assets/images/home_consultant.png';
  static const String homeMascot = 'assets/images/home_mascot.png';
  static const String homeMoodBad = 'assets/images/home_mood_bad.png';
  static const String homeMoodGreat = 'assets/images/home_mood_great.png';
  static const String homeMoodLow = 'assets/images/home_mood_low.png';
  static const String homeMoodNormal = 'assets/images/home_mood_normal.png';
  static const String homeMoodOk = 'assets/images/home_mood_ok.png';
  static const String homeMoodToday = 'assets/images/home_mood_today.png';
  static const String homeMoodUnrecorded =
      'assets/images/home_mood_unrecorded.png';
  static const String homeProfileIcon = 'assets/images/home_profile_icon.png';
  static const String homeRecordPlus = 'assets/images/home_record_plus.png';
  static const String homeSectionArrow = 'assets/images/home_section_arrow.png';
  static const String homeSectionSparkle =
      'assets/images/home_section_sparkle.png';
  static const String homeSheetClose = 'assets/images/home_sheet_close.png';
  static const String homeToolBreath = 'assets/images/home_tool_breath.png';
  static const String homeToolBubble = 'assets/images/home_tool_bubble.png';
  static const String homeToolDiary = 'assets/images/home_tool_diary.png';
  static const String homeToolMeditation =
      'assets/images/home_tool_meditation.png';
  static const String homeToolNoise = 'assets/images/home_tool_noise.png';
  static const String homeToolSleep = 'assets/images/home_tool_sleep.png';
  static const String homeToolWoodfish = 'assets/images/home_tool_woodfish.png';
  static const String icAnonymousUserAvatar =
      'assets/images/ic_anonymous_user_avatar.png';
  static const String icAppointmentDetailAi =
      'assets/images/ic_appointment_detail_ai.png';
  static const String icAppointmentDetailDecor =
      'assets/images/ic_appointment_detail_decor.png';
  static const String icAppointmentDetailHistory =
      'assets/images/ic_appointment_detail_history.png';
  static const String icAppointmentDetailTag =
      'assets/images/ic_appointment_detail_tag.png';
  static const String icBackArrow = 'assets/images/ic_back_arrow.png';
  static const String icBookingCalendar =
      'assets/images/ic_booking_calendar.png';
  static const String icBookingClock = 'assets/images/ic_booking_clock.png';
  static const String icBookingConsult = 'assets/images/ic_booking_consult.png';
  static const String icConsultRecordAi =
      'assets/images/ic_consult_record_ai.svg';
  static const String icDefaultAvatar = 'assets/images/ic_default_avatar.png';
  static const String icEvaluateStarEmpty =
      'assets/images/ic_evaluate_star_empty.png';
  static const String icEvaluateStarFilled =
      'assets/images/ic_evaluate_star_filled.png';
  static const String icGenerateSummary =
      'assets/images/ic_generate_summary.png';
  static const String icMessageConversation =
      'assets/images/ic_message_conversation.png';
  static const String icMethodText = 'assets/images/ic_method_text.png';
  static const String icMethodVideo = 'assets/images/ic_method_video.png';
  static const String icMethodVoice = 'assets/images/ic_method_voice.png';
  static const String icOrderTime = 'assets/images/ic_order_time.svg';
  static const String icPaySuccessCheck =
      'assets/images/ic_pay_success_check.svg';
  static const String icPaymentAlipay = 'assets/images/ic_payment_alipay.png';
  static const String icPaymentCheck = 'assets/images/ic_payment_check.png';
  static const String icPaymentUncheck = 'assets/images/ic_payment_uncheck.png';
  static const String icPaymentWechat = 'assets/images/ic_payment_wechat.png';
  static const String icReviewAnonymous =
      'assets/images/ic_review_anonymous.png';
  static const String icShieldRefund = 'assets/images/ic_shield_refund.png';
  static const String icStatStar = 'assets/images/ic_stat_star.png';
  static const String icStatTrophy = 'assets/images/ic_stat_trophy.png';
  static const String icStatUsers = 'assets/images/ic_stat_users.png';
  static const String icSysNoti = 'assets/images/ic_sys_noti.png';
  static const String icVerifiedBadge = 'assets/images/ic_verified_badge.png';
  static const String icWorkbenchChevronRight =
      'assets/images/ic_workbench_chevron_right.svg';
  static const String icWorkbenchLogout =
      'assets/images/ic_workbench_logout.svg';
  static const String icWorkbenchLogoutBg =
      'assets/images/ic_workbench_logout_bg.png';
  static const String icWorkbenchModeText =
      'assets/images/ic_workbench_mode_text.png';
  static const String icWorkbenchModeVideo =
      'assets/images/ic_workbench_mode_video.png';
  static const String icWorkbenchModeVoice =
      'assets/images/ic_workbench_mode_voice.png';
  static const String icWorkbenchSettings =
      'assets/images/ic_workbench_settings.png';
  static const String inputMic = 'assets/images/input_mic.png';
  static const String inputSend = 'assets/images/input_send.png';
  static const String inputSendActive = 'assets/images/input_send_active.png';
  static const String inputSendDisabled =
      'assets/images/input_send_disabled.png';
  static const String inputSmile = 'assets/images/input_smile.png';
  static const String launchBg = 'assets/images/launch_bg.png';
  static const String launchContent = 'assets/images/launch_content.png';
  static const String loginAgreementChecked =
      'assets/images/login_agreement_checked.png';
  static const String loginAgreementUnchecked =
      'assets/images/login_agreement_unchecked.png';
  static const String loginAlipay = 'assets/images/login_alipay.png';
  static const String loginCheckmark = 'assets/images/login_checkmark.png';
  static const String loginDividerLine = 'assets/images/login_divider_line.png';
  static const String loginListener = 'assets/images/login_listener.png';
  static const String loginMascot = 'assets/images/login_mascot.png';
  static const String loginRoleCounselor =
      'assets/images/login_role_counselor.png';
  static const String loginRoleUser = 'assets/images/login_role_user.png';
  static const String loginStarLarge = 'assets/images/login_star_large.png';
  static const String loginStarMedium = 'assets/images/login_star_medium.png';
  static const String loginStarSmall = 'assets/images/login_star_small.png';
  static const String loginTopPic = 'assets/images/login_top_pic.png';
  static const String loginWechat = 'assets/images/login_wechat.png';
  static const String messageAvatarChen =
      'assets/images/message_avatar_chen.png';
  /// 语音气泡声波图标（HeartHealing TUIChat message_voice_*）
  static const String messageVoiceReceiverNormal =
      'assets/images/message_voice_receiver_normal.png';
  static const String messageVoiceReceiverPlaying1 =
      'assets/images/message_voice_receiver_playing_1.png';
  static const String messageVoiceReceiverPlaying2 =
      'assets/images/message_voice_receiver_playing_2.png';
  static const String messageVoiceReceiverPlaying3 =
      'assets/images/message_voice_receiver_playing_3.png';
  static const String messageVoiceSenderNormal =
      'assets/images/message_voice_sender_normal.png';
  static const String messageVoiceSenderPlaying1 =
      'assets/images/message_voice_sender_playing_1.png';
  static const String messageVoiceSenderPlaying2 =
      'assets/images/message_voice_sender_playing_2.png';
  static const String messageVoiceSenderPlaying3 =
      'assets/images/message_voice_sender_playing_3.png';
  static const String mineAbout = 'assets/images/ic_about.png';
  static const String mineAccSafe = 'assets/images/mine_acc_safe.png';
  static const String mineAppointment = 'assets/images/mine_appointment.png';
  static const String mineArrowRight = 'assets/images/mine_arrow_right.png';
  static const String mineAssessmentRecordArrow =
      'assets/images/mine_assessment_record_arrow.png';
  static const String mineAssessmentRecordGauge =
      'assets/images/mine_assessment_record_gauge.png';
  static const String mineCancelAccount =
      'assets/images/mine_cancel_account.png';
  static const String mineFeedback = 'assets/images/mine_feedback.png';
  static const String mineLogout = 'assets/images/mine_logout.png';
  static const String minePortrait = 'assets/images/mine_portrait.png';
  static const String mineScale = 'assets/images/mine_scale.png';
  static const String mineSettings = 'assets/images/mine_settings.png';
  static const String mineSummary = 'assets/images/mine_summary.png';
  static const String mineSummaryDetailArrow =
      'assets/images/mine_summary_detail_arrow.png';
  static const String mineSwitch = 'assets/images/mine_switch.png';
  static const String optionIconAnxiety =
      'assets/images/option_icon_anxiety.png';
  static const String optionIconPressure =
      'assets/images/option_icon_pressure.png';
  static const String optionIconSleep = 'assets/images/option_icon_sleep.png';
  static const String optionIconTalk = 'assets/images/option_icon_talk.png';
  static const String quickBreath = 'assets/images/quick_breath.png';
  static const String quickVent = 'assets/images/quick_vent.png';
  static const String quickWoodfish = 'assets/images/quick_woodfish.png';
  static const String sparkleLarge = 'assets/images/sparkle_large.png';
  static const String sparkleSmall = 'assets/images/sparkle_small.png';
  static const String tabBadgeStar = 'assets/images/tab_badge_star.png';
  static const String tabDeer = 'assets/images/tab_deer.png';
  static const String tabHomeNormal = 'assets/images/tab_home_normal.png';
  static const String tabHomeSelected = 'assets/images/tab_home_selected.png';
  static const String tabMessageNormal = 'assets/images/tab_message_normal.png';
  static const String tabMessageSelected =
      'assets/images/tab_message_selected.png';
  static const String tabMineNormal = 'assets/images/tab_mine_normal.png';
  static const String tabMineSelected = 'assets/images/tab_mine_selected.png';

  // ---------- 阶段 5B 手工补充：聊天卡片图标 ----------
  // 来源：xinyuiOS TUIKit/TUIChat/Resources/TUIChat_Minimalist.bundle（仅 @3x，
  // 迁移脚本排除 TUIKit，故手工复制；重跑 migrate_ios_assets.py 不会覆盖）。
  static const String beginChatMiddleTitle =
      'assets/images/begin_chat_middle_title.png';
  static const String beginChatMiddleTime =
      'assets/images/begin_chat_middle_time.png';
  static const String remindWindowMiddleIcon =
      'assets/images/remind_window_middle_icon.png';
  static const String forEvaluateMiddleIcon =
      'assets/images/for_evaluate_middle_icon.png';
  static const String forSummaryMiddleIcon =
      'assets/images/for_summary_middle_icon.png';
  static const String summaryAdviseIcon =
      'assets/images/summary_advise_icon.png';

  /// question_assistant 工具图标（type 1-7，iOS 参照：
  /// TUIQuestionAssistantToolType.iconResourceName = question_assistant_tool_N）
  static String questionAssistantToolIcon(int type) =>
      'assets/images/question_assistant_tool_${type.clamp(1, 7)}.png';

  // ---------- 举报 / 拉黑（XYChatModule Chat.xcassets） ----------
  /// 导航栏「更多」入口（iOS nav_bar_more）
  static const String navBarMore = 'assets/images/nav_bar_more.png';

  /// 举报理由选中勾（iOS report_reason_check / gou.png，16×16）
  static const String reportReasonCheck =
      'assets/images/report_reason_check.png';

  /// 聊天图片预览下载（iOS TUIChat.bundle download，展示 31×31）
  static const String chatImageDownload =
      'assets/images/ic_chat_image_download.png';

  // ---------- 咨询室通话内图标（Figma #571:5052，@2x → ÷2 渲染） ----------
  // 整图含圆形底+字形（非裸图标），显示按 ÷2：116→58、72→36。
  /// 顶部最小化（顶部操作1 #571:5078，72÷2=36）
  static const String icRoomMinimize = 'assets/images/ic_room_minimize.png';
  /// 麦克风（按钮1 #571:5107，116÷2=58）
  static const String icRoomMic = 'assets/images/ic_room_mic.png';
  /// 麦克风-已关（#571:4778，116÷2=58）
  static const String icRoomMicOff = 'assets/images/ic_room_mic_off.png';
  /// 摄像头（按钮2 #571:5115，116÷2=58）
  static const String icRoomCamera = 'assets/images/ic_room_camera.png';
  /// 摄像头-已关（#571:4787，116÷2=58）
  static const String icRoomCameraOff = 'assets/images/ic_room_camera_off.png';
  /// 聊天（按钮3 #571:5137，116÷2=58）
  static const String icRoomChat = 'assets/images/ic_room_chat.png';
  /// 挂断（按钮4 #571:5147，116÷2=58）
  static const String icRoomHangup = 'assets/images/ic_room_hangup.png';
}
